name: Deploy Server

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for the backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install Server Dependencies
        working-directory: ./server
        run: npm install --legacy-peer-deps

      # Step 4: Deploy using Serverless Framework
      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Deploy to AWS Lambda
        working-directory: ./server
        run: |
          npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
